services:
  - type: web
    name: messenger-bot
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
databases:
  - name: mydb
